#!/usr/bin/perl -w

use CSO;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new(Name => "CSO",
					       ReceiveHandler => \&Receive);
$UNIVERSAL::agent->DoNotDaemonize(1);
$UNIVERSAL::cso = CSO->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::cso->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::cso->Execute();
