#!/usr/bin/perl -w

use CSO2;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (
   Name => "CSO2",
   ReceiveHandler => \&Receive,
  );
$UNIVERSAL::agent->DoNotDaemonize(1);
$UNIVERSAL::cso2 = CSO2->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::cso2->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::cso2->Execute();
